# Generated by Django 4.1.6 on 2023-02-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='area',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='culture',
        ),
        migrations.AddField(
            model_name='plot',
            name='season',
            field=models.ManyToManyField(to='app.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.culture')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plot')),
            ],
            options={
                'verbose_name_plural': 'plantings',
            },
        ),
    ]
