# Generated by Django 4.1.6 on 2023-02-11 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_plot_area_remove_plot_culture_plot_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='culture',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.culture'),
        ),
    ]
